Repository boostcampwm-2024/and01-dreamDiary, pull requests merged in 2024-12, with the labels that each got.

#237 [feat] 커뮤니티 post 카드 정상화
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
Labels: ✨ Enhancement

#240 [feat] 스크롤시 bottombar를 숨김
  core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/HomeBottomNavigation.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
Labels: ✨ Enhancement

#241 [feat] 검색 추가
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiariesByTitleUseCase.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetSearchSuggestions.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/search/DiarySearchScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/search/DiarySearchUiState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/search/DiarySearchViewModel.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#242 [docs] readme 업데이트
  README.md
Labels: 📚 Documentation

#239 [fix] server timestamp를 map으로 추가하지 않게 변경
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/firestore/model/FirestoreAddCommunityPostRequest.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
Labels: 🛠 Refactor

#246 [docs] readme 업데이트
  README.md
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
Labels: 📚 Documentation

#243 [feat] label 삭제 기능 추가
  README.md
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/DeleteLabelUseCase.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelItem.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelSelectionDialog.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#269 [feat] 로그아웃 다이얼로그
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/res/values/strings.xml
Labels: 📲 UI/UX

#275 [fix] 커뮤니티 카드모양에 맞춘 클릭 영역
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
Labels: 🐞 Bug, 📲 UI/UX

#272 [fix] 셋팅 아래 8패딩 서순 변경
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
Labels: 🐞 Bug, 📲 UI/UX

#276 [fix] 달력 bottomSheet listItem 가로 크기 늘리기
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBottomSheet.kt
Labels: 🐞 Bug

#273 [fix] takePersistableUriPermission의 익셉션 처리
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
Labels: 🐞 Bug

#278 [fix] 일기 작성 성공 toast 제거
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/res/values/strings.xml
Labels: 🐞 Bug

#280 [feat] fcm 설정
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/DreamDiaryApplication.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommentRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/di/RepositoryModule.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/SendCommentNotificationUseCase.kt
  core/fcm/.gitignore
  core/fcm/build.gradle.kts
  core/fcm/consumer-rules.pro
  core/fcm/proguard-rules.pro
  core/fcm/src/androidTest/java/com/boostcamp/dreamteam/dreamdiary/core/fcm/ExampleInstrumentedTest.kt
  core/fcm/src/main/AndroidManifest.xml
  core/fcm/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/fcm/DreamDiaryFirebaseMessagingService.kt
  core/fcm/src/test/java/com/boostcamp/dreamteam/dreamdiary/core/fcm/ExampleUnitTest.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/CommunityPostDetail.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostDetailUi.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨ Enhancement

#283 [feat] 가로 스크롤로 탭 전환 가능
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
Labels: ✨ Enhancement

#282 [chore] 커뮤니티 로딩중 shimmer 효과 추가
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/boostcamp/dreamteam/dreamdiary/designsystem/component/Card.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  gradle/libs.versions.toml
Labels: ✨ Enhancement

#284 [fix] 공유 -> 게시 이름 변경
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryMenuButton.kt
  feature/diary/src/main/res/values/strings.xml
Labels: 📲 UI/UX

#281 [feat] comment ui 수정
  README.md
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/GetPostIsLikeUseCase.kt
  core/ui/src/main/res/values/strings.xml
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailComment.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/CommentUi.kt
  feature/community/src/main/res/values/strings.xml
Labels: 📲 UI/UX

#285 [feat] 설정화면의 미구현 기능은 toast 메시지를 띄우는 것으로 변경
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/component/SettingOption.kt
Labels: ✨ Enhancement

#286 [fix] 제목과 컨텐트가 없을 때 작성x로 수정
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
  feature/community/src/main/res/values/strings.xml
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/res/values/strings.xml
Labels: 🐞 Bug

#288 [feat] community detail 날짜 추가
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailPostCard.kt
Labels: 📲 UI/UX

#291 [feat] 댓글 삭제 기능
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommentRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/DeleteCommentUseCase.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailEvent.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityCommentsMenuButton.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailComment.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/CommentUi.kt
  feature/community/src/main/res/values/strings.xml
Labels: 📲 UI/UX, ✨ Enhancement, 📝Story

#294 [refactor] 위젯 모듈 의존성 제거
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/manager/DiaryWidgetManger.kt
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/DreamDiaryAppState.kt
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/widget/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/DiaryWriteWidgetReceiver.kt
  feature/widget/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/util/WidgetUtil.kt
Labels: 🛠 Refactor
