Repository boostcampwm-2024/and01-dreamDiary, pull requests merged in 2024-11, with the labels that each got.

#32 chore: hilt-navigation-compose 추가
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🔄 Dependency Update

#31 feat: feature 모듈 생성
  feature/.gitignore
  feature/diary/.gitignore
  feature/diary/build.gradle.kts
  feature/diary/consumer-rules.pro
  feature/diary/proguard-rules.pro
  feature/diary/src/androidTest/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/ExampleInstrumentedTest.kt
  feature/diary/src/main/AndroidManifest.xml
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryListScreen.kt
  feature/diary/src/test/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 🔄 Dependency Update

#35 [feat] 나의 일기 목록(리스트) 화면 구현
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Diary.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Label.kt
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryListScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/components/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/components/DiaryListTab.kt
  gradle/libs.versions.toml
Labels: ✨ Enhancement, 📝Story

#39 [chore] 빌드 속도 향상
  build-logic/gradle.properties
  gradle.properties
Labels: ✨ Enhancement

#45 docs: pull_request_template.md
  .github/pull_request_template.md
Labels: 📚 Documentation

#44 [feat] hilt application 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/DreamDiaryApplication.kt
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/MainActivity.kt
Labels: 🔄 Dependency Update

#47 [chore] 어노테이션 관련 lint 규칙 수정
  .editorconfig
Labels: 🔄 Dependency Update

#41 [feat] 뷰모델 생성
  core/domain/build.gradle.kts
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDiariesUseCase.kt
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryHomeUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryViewModel.kt
Labels: ✨ Enhancement

#49 [feat] diary write viewmodel 생성
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
Labels: ✨ Enhancement

#50 [feat] home navigation 연결
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendarTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryListTab.kt
Labels: ✨ Enhancement

#52 [feat] 파이어베이스 연결
  app/.gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  core/data/build.gradle.kts
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/FirebaseDataSource.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DiaryRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDiariesUseCase.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Diary.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Label.kt
  gradle/libs.versions.toml
Labels: ✨ Enhancement

#58 [feat] preview에 테마 적용
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryListTab.kt
Labels: ✨ Enhancement

#62 [refactor] home 잘못된 패키지 이동
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryHomeUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
Labels: 🛠 Refactor

#64 [refactor] domain model과 ui model 분리
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryListTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/models/DiaryUi.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/models/LabelUi.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/models/vos/DisplayableDateTime.kt
Labels: 🛠 Refactor

#65 [feat] 로그인UI 작성
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/LoginScreen.kt
  feature/diary/src/main/res/drawable/github_icon.xml
  feature/diary/src/main/res/drawable/google_icon.xml
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement, 📝Story

#66 [feat] label selection UI
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
Labels: 📲 UI/UX, 📝Story

#70 [feat] 날짜만 표시되는 달력 구현
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendar.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendarBody.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendarTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendarYearMonthPicker.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#92 [chore] timber 라이브러리 추가
  app/build.gradle.kts
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/DreamDiaryApplication.kt
  build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/AndroidLibraryConventionPlugin.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/FirebaseDataSource.kt
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  gradle/libs.versions.toml
Labels: ✨ Enhancement

#94 [refactor] tab별 uistate 클래스 분리
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryCalendarTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryHomeTabListUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/models/DiaryUi.kt
Labels: 🛠 Refactor

#98 [feat] feature, compose build logic
  app/build.gradle.kts
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/AndroidApplicationComposeConventionPlugin.kt
  build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/AndroidFeatureConventionPlugin.kt
  build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/AndroidLibraryComposeConventionPlugin.kt
  build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/AndroidLibraryConventionPlugin.kt
  build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/ProjectExtensions.kt
  build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/extension/AndroidCompose.kt
  build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/extension/ProjectExtensions.kt
  core/designsystem/build.gradle.kts
  feature/auth/build.gradle.kts
  feature/diary/build.gradle.kts
  gradle/libs.versions.toml
Labels: 🔄 Dependency Update

#102 [chore] ktlint 속도를 더 빠르게 하기 위해 외부에서 확인
  .github/workflows/lint_and_build.yml
Labels: ✨ Enhancement

#108 [fix] dynamic color를 사용하지 않도록 변경
  core/designsystem/src/main/java/com/boostcamp/dreamteam/dreamdiary/designsystem/theme/Theme.kt
Labels: 🐞 Bug

#109 [chore] 폴더명 변경
  core/data/build.gradle.kts
  core/data/schema/com.boostcamp.dreamteam.dreamdiary.core.data.database.DreamDiaryDatabase/1.json
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Label.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendar.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBody.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarYearMonthPicker.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryCalendarTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryHomeTabCalendarUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryHomeTabListUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/LabelUi.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/vo/DisplayableDateTime.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/LabelItem.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/LabelSelectionDialog.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
Labels: 🐞 Bug

#116 [docs] README.md 잘못된 년도 수정
  README.md
Labels: 🐞 Bug

#115 [feat] 자동 로그인, 건너 뛰기
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInNavigation.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInScreen.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInViewModel.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/model/SignInState.kt
  gradle/libs.versions.toml
Labels: ✨ Enhancement

#118 [feat] 기준에 해당하는 필드 값 추가
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBody.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt
Labels: 🛠 Refactor

#119 [feat] bottom sheet에 일기 목록 표시
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendar.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBody.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBottomSheet.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryCalendarTab.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#122 [feat] setting-ui
  feature/setting/.gitignore
  feature/setting/build.gradle.kts
  feature/setting/consumer-rules.pro
  feature/setting/proguard-rules.pro
  feature/setting/src/androidTest/java/com/boostcamp/dreamteam/dreamdiary/setting/ExampleInstrumentedTest.kt
  feature/setting/src/main/AndroidManifest.xml
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/res/values/strings.xml
  feature/setting/src/test/java/com/boostcamp/dreamteam/dreamdiary/setting/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 📲 UI/UX, ✨ Enhancement

#124 [feat] 달력에 저장된 일기 표시
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/Mapper.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiariesInRangeByUseCase.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Diary.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Label.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt
Labels: ✨ Enhancement

#123 [feat] 깃허브 로그인
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInScreen.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInViewModel.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/model/SignInEvent.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/model/SignInState.kt
  feature/auth/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ Enhancement, 📦Epic, 📝Story

#130 [fix] 라벨 검색 시 버그 수정
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/LabelUi.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/DiaryWriteScreenHeader.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/LabelSelectionDialog.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
  feature/diary/src/main/res/values/strings.xml
Labels: 🐞 Bug, 📝Story

#131 [feat] setting screen을 bottom bar 연결
  app/build.gradle.kts
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
Labels: 📲 UI/UX, ✨ Enhancement

#132 [feat] 꿈일기 상세 화면
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/DreamDiaryWithLabels.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/Mapper.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiaryUseCase.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailNavigation.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/model/DiaryDetailUiState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/DiaryWriteScreenHeader.kt
  feature/diary/src/main/res/values/strings.xml
Labels: 📲 UI/UX, ✨ Enhancement

#134 [fix] topbar ui 수정
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/res/values/strings.xml
Labels: 📲 UI/UX

#135 [feat] ktlint, build 작업 분리
  .github/workflows/build.yml
  .github/workflows/ktlin_check.yml
Labels: 🚀 Performance

#139 [feat] nested navigation으로 변경
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailNavigation.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteNavigation.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingViewModel.kt
  gradle.properties
Labels: ✨ Enhancement

#141 [feat] widget 모듈 생성
  feature/widget/.gitignore
  feature/widget/build.gradle.kts
  feature/widget/consumer-rules.pro
  feature/widget/proguard-rules.pro
  feature/widget/src/androidTest/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/ExampleInstrumentedTest.kt
  feature/widget/src/main/AndroidManifest.xml
  feature/widget/src/test/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨ Enhancement

#140 [feat] card에 메뉴 버튼 추가
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#142 [feat] 로그아웃 구현
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInScreen.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInViewModel.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingViewModel.kt
  feature/setting/src/main/res/values/strings.xml
Labels: ✨ Enhancement, 📝Story

#143 [feat] debug.keystore
  .github/workflows/build.yml
  .gitignore
  app/build.gradle.kts
  local.properties.template
Labels: 🔄 Dependency Update

#145 [feat] SNS 계정 확인
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingViewModel.kt
Labels: ✨ Enhancement, 📝Story

#147 [feat] diary write widget 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/widget/src/main/AndroidManifest.xml
  feature/widget/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/DiaryWriteAction.kt
  feature/widget/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/DiaryWriteWidget.kt
  feature/widget/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/WidgetReceiver.kt
  feature/widget/src/main/res/drawable/ic_android.xml
  feature/widget/src/main/res/values/strings.xml
  feature/widget/src/main/res/xml-v31/diary_write_appwidget_info.xml
  feature/widget/src/main/res/xml/diary_write_appwidget_info.xml
Labels: ✨ Enhancement

#148 [feat] 재활용하기 위한 카드 구현
  core/designsystem/src/main/java/com/boostcamp/dreamteam/dreamdiary/designsystem/component/Card.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt
Labels: ✨ Enhancement

#151 [feat] 홈 다이어리 라벨 필터UI
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiariesByFilterUseCase.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement, 📝Story

#152 [feat] 공통 AsyncImage 컴포넌트 추가
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/boostcamp/dreamteam/dreamdiary/designsystem/component/AsyncImage.kt
  core/designsystem/src/main/res/drawable/image_preview.jpg
  core/designsystem/src/main/res/values/strings.xml
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/DiaryWriteScreenBody.kt
Labels: ✨ Enhancement

#154 [refactor] edit component로 이름 변경
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryContentEditor.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryEditor.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryInfosEditor.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelItem.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelSelectionDialog.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
Labels: ✨ Enhancement

#155 [feat] 일기 편집 네비게이션 연결
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#160 [fix] 작성 화면에서 스크롤 시 padding이 이상하게 적용되는 문제 해결
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
Labels: 🐞 Bug

#159 [feat] 일기 상세화면에 수정/삭제 메뉴 추가
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/model/DiaryDetailUiState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
Labels: ✨ Enhancement

#163 [fix] 라벨이 수정되지 않는 문제 해결
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
Labels: 🐞 Bug

#164 [feat] 일기 작성 및 수정 후 상세화면 자동 이동
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/AddDreamDiaryWithContentsUseCase.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt
Labels: ✨ Enhancement

#165 [feat] logo 추가
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: ✨ Enhancement

#167 [feat] 홈 화면 일기 삭제
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/DeleteDreamDiariesUseCase.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
Labels: ✨ Enhancement

#168 [feat] 상세화면 - 일기 삭제 기능 구현
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/model/DiaryDetailEvent.kt
Labels: ✨ Enhancement

#169 [feat] 일기 삭제 정책을 soft delete로 변경
  core/data/schema/com.boostcamp.dreamteam.dreamdiary.core.data.database.DreamDiaryDatabase/1.json
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/DreamDiaryEntity.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
Labels: ✨ Enhancement

#170 [feat] 비어있는 리스트 화면 꾸미기
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#171 [feat] 라벨 편집 UI 구성
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryInfosEditor.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelItem.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelSelectionDialog.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#173 [feat] signin screen에 로고
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInScreen.kt
  feature/auth/src/main/res/drawable/google_icon.xml
  feature/auth/src/main/res/drawable/logo.png
  feature/auth/src/main/res/values/strings.xml
Labels: 📲 UI/UX, ✨ Enhancement

#174 [hotfix] 잘못 설정된 key 수정
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
Labels: 🐞 Bug

#175 [chore] configuration-cache를 사용하도록 설정
  gradle.properties
Labels: 🚀 Performance

#176 [feat] bottom navigation 선택된 아이콘 색칠하기
  core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/HomeBottomNavItem.kt
  core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/HomeBottomNavigation.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
Labels: 📲 UI/UX, ✨ Enhancement

#177 [feat] 비어있는 CommunityListScreen 생성
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListUiState.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/DiaryUi.kt
Labels: ✨ Enhancement

#183 [fix] community navigation 캡슐화
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
Labels: ✨ Enhancement

#178 [feat] 꿈 일기 정렬 버튼 추가
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryHomeTabListUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#179 [feat] 설정 - 백업 ui
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingBackupScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/component/SettingCategory.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/component/SettingOption.kt
  feature/setting/src/main/res/values/strings.xml
Labels: 📲 UI/UX

#186 [feat] 일기 정렬 로직 추가
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/model/DiarySort.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiariesByFilterUseCase.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryHomeTabListUIState.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
Labels: ✨ Enhancement

#188 [feat] 커뮤니티 일기 카드 구현
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/DiaryUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/UserUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/DisplayableDateTime.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/DisplayableDateTimeFormatter.kt
  feature/community/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#197 [fix] community 피드백 반영
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/DisplayableDateTime.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/DisplayableDateTimeFormatter.kt
Labels: 🐞 Bug

#195 [feat] setting backup screen navigation 연결
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/component/SettingOption.kt
Labels: ✨ Enhancement

#200 [feat] 알림 세팅 스크린추가, 알림 기능 정상화
  app/build.gradle.kts
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/DreamDiaryApplication.kt
  core/notification/.gitignore
  core/notification/build.gradle.kts
  core/notification/consumer-rules.pro
  core/notification/proguard-rules.pro
  core/notification/src/androidTest/java/com/boostcamp/dreamteam/dreamdiary/notification/ExampleInstrumentedTest.kt
  core/notification/src/main/AndroidManifest.xml
  core/notification/src/main/java/com/boostcamp/dreamteam/dreamdiary/notification/Notification.kt
  core/notification/src/main/java/com/boostcamp/dreamteam/dreamdiary/notification/ScreenOffTimeTracker.kt
  core/notification/src/main/java/com/boostcamp/dreamteam/dreamdiary/notification/ScreenTrackingService.kt
  core/notification/src/main/res/values/strings.xml
  core/notification/src/test/java/com/boostcamp/dreamteam/dreamdiary/notification/ExampleUnitTest.kt
  feature/diary/build.gradle.kts
  feature/diary/src/main/AndroidManifest.xml
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNotificationScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNotificationViewModel.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: ✨ Enhancement, 📝Story

#204 [feat] 알람누르면 잔시간 가지고 작성페이지로
  core/notification/src/main/java/com/boostcamp/dreamteam/dreamdiary/notification/ScreenOffTimeTracker.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
Labels: ✨ Enhancement

#205 [feat] community firestore db
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/CommunityRemoteDataSource.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/AddCommunityPostUseCase.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/GetCommunityPostUseCase.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Comment.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/CommunityDreamPost.kt
  core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/PagingIndexKey.kt
  feature/community/build.gradle.kts
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListUiState.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/PagingIndexKey.kt
Labels: ✨ Enhancement

#213 [feat] 공유 시 일기 내용 자동 입력
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/PostContentUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreenState.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/component/CommunityEditor.kt
  feature/community/src/main/res/values/strings.xml
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryMenuButton.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#216 [fix] `ForegroundServiceStartNotAllowedException`이 발생하는 문제 해결
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/DreamDiaryApplication.kt
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/MainActivity.kt
Labels: 🐞 Bug

#217 [feat] community comment 구현
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/CommentDataSource.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/CommunityRemoteDataSource.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/dto/CommentRequest.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/dto/CommentResponse.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/FirebaseCommentPagingSource.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/FirebaseCommunityPostPagingSource.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/firestore/model/FirestoreAddCommunityPostRequest.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/firestore/model/FirestoreGetCommunityPostResponse.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommentRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/AddCommentUseCase.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/AddCommunityPostUseCase.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/GetCommentUseCase.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/GetCommunityPostUseCase.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Author.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Comment.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/community/CommunityPostList.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/PostContentUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteViewModel.kt
Labels: ✨ Enhancement

#219 [fix] 커뮤니티 작성 화면 버그 수정
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/component/CommunityEditor.kt
Labels: 🐞 Bug

#220 [feat] 홈 화면 스크롤 시 topappbar 숨기기
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
Labels: ✨ Enhancement

#222 [feat] padding 수정, placeholder 숨기기
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/component/CommunityEditor.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
Labels: ✨ Enhancement

#224 [feat] firebase creashlytics 추가
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ✨ Enhancement

#223 [feat] 로그인x 일때 일부기능이 로그인 화면으로 이동하기로 변경
  app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
  core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/component/GoToSignInDialog.kt
  core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/component/OutlineSignInButton.kt
  core/ui/src/main/res/values/strings.xml
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInNavigation.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInScreen.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInViewModel.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/model/SignInEvent.kt
  feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/model/SignInState.kt
  feature/auth/src/main/res/values/strings.xml
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
  feature/community/src/main/res/drawable/github_icon.xml
  feature/community/src/main/res/drawable/google_icon.xml
  feature/community/src/main/res/values/strings.xml
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingViewModel.kt
Labels: ✨ Enhancement

#225 [docs] readme.md 내용 추가
  README.md
Labels: 📚 Documentation

#221 [feat] detail screen 연결, community list에
  README.md
  app/src/main/AndroidManifest.xml
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/dto/CommentRequest.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/dto/CommentResponse.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/dto/CommunityPostRequest.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/dto/CommunityPostResponse.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/FirebaseCommentPagingSource.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/firestore/model/FirestoreAddCommunityPostRequest.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/firestore/model/FirestoreGetCommunityPostResponse.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommentRepository.kt
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/AddCommunityPostUseCase.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/GetCommunityPostUseCase.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/GetCommunityPostsUseCase.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Comment.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/CommunityPostDetail.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/community/CommunityPostList.kt
  core/storage/.gitignore
  core/storage/build.gradle.kts
  core/storage/consumer-rules.pro
  core/storage/proguard-rules.pro
  core/storage/src/androidTest/java/com/boostcamp/dreamteam/dreamdiary/storage/ExampleInstrumentedTest.kt
  core/storage/src/main/AndroidManifest.xml
  core/storage/src/main/java/com/boostcamp/dreamteam/dreamdiary/storage/AndroidStorageManager.kt
  core/storage/src/main/java/com/boostcamp/dreamteam/dreamdiary/storage/StorageManager.kt
  core/storage/src/main/java/com/boostcamp/dreamteam/dreamdiary/storage/StorageModule.kt
  core/storage/src/test/java/com/boostcamp/dreamteam/dreamdiary/storage/ExampleUnitTest.kt
  feature/community/build.gradle.kts
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailComment.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/CommentUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostDetailUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/UserUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/component/CommunityEditor.kt
  feature/community/src/main/res/drawable/github_icon.xml
  feature/community/src/main/res/drawable/google_icon.xml
  feature/diary/build.gradle.kts
  feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingViewModel.kt
  settings.gradle.kts
Labels: 📲 UI/UX, ✨ Enhancement

#226 [feat] 커뮤니티 당겨서 새로고침 로직 추가
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
Labels: ✨ Enhancement

#228 [feat] comment add
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailEvent.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailUiState.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt
Labels: ✨ Enhancement

#229 [feat] 홈 화면 로딩 중에는 아무것도 보여주지 않도록 변경
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
Labels: ✨ Enhancement

#230 [fix] 커뮤니티 목록 로그인 하지 않을 경우 스크롤 방지
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
Labels: ✨ Enhancement

#232 [feat] 신규 댓글 입력창 크기 줄이기
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
Labels: ✨ Enhancement

#235 [feat] 라벨 수정 기능 제거
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryInfosEditor.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelItem.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelSelectionDialog.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt
Labels: ✨ Enhancement

#233 [feat] 공유 성공 후 바로 상세 화면으로 이동
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteEvent.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreenState.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteViewModel.kt
  feature/community/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#234 [feat] community list 화면 좋아요
  core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
  core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/GetCommunityPostsUseCase.kt
  core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/community/CommunityPostList.kt
  core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/util/FlowExtension.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailComment.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListEvent.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListUiState.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostUi.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteEvent.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreenState.kt
  feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteViewModel.kt
  feature/community/src/main/res/values/strings.xml
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryInfosEditor.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelItem.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelSelectionDialog.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
  feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt
Labels: ✨ Enhancement
